### ISSUE TITLE
v1.4.4 source  building error

### ISSUE THREAD

**Issue by junlicn** [cenkalti/rain#12]
get source  and unzip
# cd rain-1.4.4/
# go  build

go: downloading github.com/zeebo/bencode v1.0.0
go: downloading github.com/hokaccha/go-prettyjson v0.0.0-20190818114111-108c894c2c0e
go: downloading github.com/urfave/cli v1.22.4
go: extracting github.com/zeebo/bencode v1.0.0
go: extracting github.com/urfave/cli v1.22.4
go: downloading github.com/cenkalti/log v0.0.0-20180808170110-e1cf6d40cbc3
go: downloading github.com/multiformats/go-multihash v0.0.13
go: downloading github.com/powerman/rpc-codec v1.1.4
go: extracting github.com/cenkalti/log v0.0.0-20180808170110-e1cf6d40cbc3
go: extracting github.com/hokaccha/go-prettyjson v0.0.0-20190818114111-108c894c2c0e
go: extracting github.com/multiformats/go-multihash v0.0.13
go: downloading github.com/boltdb/bolt v1.3.1
go: extracting github.com/boltdb/bolt v1.3.1
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading gopkg.in/yaml.v2 v2.2.8
go: extracting github.com/powerman/rpc-codec v1.1.4
go: extracting gopkg.in/yaml.v2 v2.2.8
go: extracting github.com/mattn/go-isatty v0.0.12
go: downloading golang.org/x/sys v0.0.0-20200413165638-669c56c373c4
go: downloading github.com/cenkalti/boltbrowser v0.0.0-20190327195521-ebed13c76690
go: downloading golang.org/x/crypto v0.0.0-20200414173820-0848c9571904
go: extracting github.com/cenkalti/boltbrowser v0.0.0-20190327195521-ebed13c76690
go: downloading github.com/br0xen/termbox-util v0.0.0-20200220160819-dc6d6950ba00
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/mr-tron/base58 v1.1.3
go: extracting github.com/br0xen/termbox-util v0.0.0-20200220160819-dc6d6950ba00
go: extracting github.com/mr-tron/base58 v1.1.3
go: extracting github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0
go: downloading github.com/hashicorp/go-multierror v1.1.0
go: downloading github.com/multiformats/go-varint v0.0.5
go: downloading github.com/nsf/termbox-go v0.0.0-20200418040025-38ba6e5628f1
go: downloading github.com/jroimartin/gocui v0.4.0
go: downloading github.com/cenkalti/backoff/v3 v3.2.2
go: extracting github.com/cpuguy83/go-md2man/v2 v2.0.0
go: downloading github.com/nictuku/dht v0.0.0-20200512202754-8008414d60e5
go: extracting github.com/hashicorp/go-multierror v1.1.0
go: extracting github.com/multiformats/go-varint v0.0.5
go: downloading go.etcd.io/bbolt v1.3.5
go: extracting github.com/nsf/termbox-go v0.0.0-20200418040025-38ba6e5628f1
go: extracting github.com/jroimartin/gocui v0.4.0
go: extracting golang.org/x/sys v0.0.0-20200413165638-669c56c373c4
go: extracting github.com/nictuku/dht v0.0.0-20200512202754-8008414d60e5
go: extracting github.com/cenkalti/backoff/v3 v3.2.2
go: downloading github.com/gofrs/uuid v3.2.0+incompatible
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/mattn/go-runewidth v0.0.9
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/nictuku/nettools v0.0.0-20150117095333-8867a2107ad3
go: extracting go.etcd.io/bbolt v1.3.5
go: extracting github.com/gofrs/uuid v3.2.0+incompatible
go: downloading github.com/fatih/structs v1.1.0
go: extracting github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/minio/blake2b-simd v0.0.0-20160723061019-3f5f724cb5b1
go: extracting github.com/mattn/go-runewidth v0.0.9
go: downloading github.com/jackpal/bencode-go v0.0.0-20180813173944-227668e840fa
go: extracting github.com/russross/blackfriday/v2 v2.0.1
go: extracting github.com/minio/blake2b-simd v0.0.0-20160723061019-3f5f724cb5b1
go: downloading github.com/google/btree v1.0.0
go: extracting golang.org/x/crypto v0.0.0-20200414173820-0848c9571904
go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: downloading github.com/fatih/color v1.9.0
go: extracting github.com/nictuku/nettools v0.0.0-20150117095333-8867a2107ad3
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/fatih/structs v1.1.0
go: downloading github.com/cenkalti/go-metrics v0.0.0-20190910102919-35c391953d1c
go: extracting github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: downloading github.com/juju/ratelimit v1.0.1
go: extracting github.com/cenkalti/go-metrics v0.0.0-20190910102919-35c391953d1c
go: extracting github.com/google/btree v1.0.0
go: downloading github.com/youtube/vitess v2.2.0-rc.1+incompatible
go: extracting github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/fatih/color v1.9.0
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: extracting github.com/juju/ratelimit v1.0.1
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading github.com/mattn/go-colorable v0.1.6
go: extracting github.com/jackpal/bencode-go v0.0.0-20180813173944-227668e840fa
go: extracting github.com/mattn/go-colorable v0.1.6
go: extracting github.com/shurcooL/sanitized_anchor_name v1.0.0
go: extracting github.com/minio/sha256-simd v0.1.1
go: extracting github.com/youtube/vitess v2.2.0-rc.1+incompatible
go: finding github.com/boltdb/bolt v1.3.1
go: finding github.com/cenkalti/boltbrowser v0.0.0-20190327195521-ebed13c76690
go: finding github.com/cenkalti/log v0.0.0-20180808170110-e1cf6d40cbc3
go: finding github.com/hashicorp/go-multierror v1.1.0
go: finding github.com/mattn/go-isatty v0.0.12
go: finding golang.org/x/sys v0.0.0-20200413165638-669c56c373c4
go: finding github.com/br0xen/termbox-util v0.0.0-20200220160819-dc6d6950ba00
go: finding github.com/fatih/structs v1.1.0
go: finding github.com/hashicorp/errwrap v1.0.0
go: finding github.com/nsf/termbox-go v0.0.0-20200418040025-38ba6e5628f1
go: finding github.com/jroimartin/gocui v0.4.0
go: finding github.com/hokaccha/go-prettyjson v0.0.0-20190818114111-108c894c2c0e
go: finding github.com/multiformats/go-multihash v0.0.13
go: finding github.com/mitchellh/go-homedir v1.1.0
go: finding github.com/powerman/rpc-codec v1.1.4
go: finding github.com/urfave/cli v1.22.4
go: finding github.com/zeebo/bencode v1.0.0
go: finding github.com/fatih/color v1.9.0
go: finding gopkg.in/yaml.v2 v2.2.8
go: finding github.com/mattn/go-runewidth v0.0.9
go: finding github.com/mattn/go-colorable v0.1.6
go: finding github.com/cpuguy83/go-md2man/v2 v2.0.0
go: finding github.com/minio/blake2b-simd v0.0.0-20160723061019-3f5f724cb5b1
go: finding github.com/minio/sha256-simd v0.1.1
go: finding github.com/russross/blackfriday/v2 v2.0.1
go: finding github.com/mr-tron/base58 v1.1.3
go: finding github.com/multiformats/go-varint v0.0.5
go: finding github.com/spaolacci/murmur3 v1.1.0
go: finding github.com/shurcooL/sanitized_anchor_name v1.0.0
go: finding golang.org/x/crypto v0.0.0-20200414173820-0848c9571904
go: finding github.com/cenkalti/backoff/v3 v3.2.2
go: finding github.com/google/btree v1.0.0
go: finding github.com/cenkalti/go-metrics v0.0.0-20190910102919-35c391953d1c
go: finding github.com/juju/ratelimit v1.0.1
go: finding go.etcd.io/bbolt v1.3.5
go: finding github.com/gofrs/uuid v3.2.0+incompatible
go: finding github.com/nictuku/dht v0.0.0-20200512202754-8008414d60e5
go: finding github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: finding github.com/jackpal/bencode-go v0.0.0-20180813173944-227668e840fa
go: finding github.com/nictuku/nettools v0.0.0-20150117095333-8867a2107ad3
go: finding github.com/youtube/vitess v2.2.0-rc.1+incompatible
# github.com/cenkalti/rain
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x698dec, 0x16)
        /usr/lib/go-1.13/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc00c000000, 0x4000000, 0x878c38)
        /usr/lib/go-1.13/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x861120, 0x130000, 0x7fff696dba50, 0x435a57)
        /usr/lib/go-1.13/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x861120, 0x98, 0xffffffff)
        /usr/lib/go-1.13/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x861120, 0x98, 0x878c48, 0x20300200000000)
        /usr/lib/go-1.13/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x861120, 0x98, 0x101, 0x7ffba84ebfff)
        /usr/lib/go-1.13/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/lib/go-1.13/src/runtime/mheap.go:1093 +0x4c
runtime.(*mheap).alloc(0x861120, 0x98, 0x10101, 0x200)
        /usr/lib/go-1.13/src/runtime/mheap.go:1092 +0x8a
runtime.largeAlloc(0x12ff10, 0x7fff696d0101, 0x456e9a)
        /usr/lib/go-1.13/src/runtime/malloc.go:1138 +0x97
runtime.mallocgc.func1()
        /usr/lib/go-1.13/src/runtime/malloc.go:1033 +0x46
runtime.systemstack(0x4584c4)
        /usr/lib/go-1.13/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /usr/lib/go-1.13/src/runtime/proc.go:1146

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/lib/go-1.13/src/runtime/asm_amd64.s:330 fp=0xc00bdb0cc0 sp=0xc00bdb0cb8 pc=0x4585c0
runtime.mallocgc(0x12ff10, 0x63c200, 0x1, 0x0)
        /usr/lib/go-1.13/src/runtime/malloc.go:1032 +0x895 fp=0xc00bdb0d60 sp=0xc00bdb0cc0 pc=0x40c225
runtime.makeslice(0x63c200, 0x12ff10, 0x12ff10, 0x0)
        /usr/lib/go-1.13/src/runtime/slice.go:49 +0x6c fp=0xc00bdb0d90 sp=0xc00bdb0d60 pc=0x4437fc
bytes.makeSlice(0x12ff10, 0x0, 0x0, 0x0)
        /usr/lib/go-1.13/src/bytes/buffer.go:229 +0x77 fp=0xc00bdb0df8 sp=0xc00bdb0d90 pc=0x4c90e7
bytes.(*Buffer).grow(0xc00a489a10, 0xf0, 0xf0)
        /usr/lib/go-1.13/src/bytes/buffer.go:142 +0x15b fp=0xc00bdb0e48 sp=0xc00bdb0df8 pc=0x4c8abb
bytes.(*Buffer).Write(0xc00a489a10, 0xc00b2c8b60, 0xf0, 0xf8, 0xf0, 0x7f, 0x410)
        /usr/lib/go-1.13/src/bytes/buffer.go:172 +0xdd fp=0xc00bdb0e78 sp=0xc00bdb0e48 pc=0x4c8d2d
compress/flate.(*dictWriter).Write(0xc0080d06f0, 0xc00b2c8b60, 0xf0, 0xf8, 0xf0, 0x0, 0x0)
        /usr/lib/go-1.13/src/compress/flate/deflate.go:696 +0x51 fp=0xc00bdb0ec0 sp=0xc00bdb0e78 pc=0x4ded31
compress/flate.(*huffmanBitWriter).write(...)
        /usr/lib/go-1.13/src/compress/flate/huffman_bit_writer.go:136
compress/flate.(*huffmanBitWriter).writeCode(0xc00b2c8b40, 0xc0000a0197)
        /usr/lib/go-1.13/src/compress/flate/huffman_bit_writer.go:347 +0x104 fp=0xc00bdb0f08 sp=0xc00bdb0ec0 pc=0x4e08a4
compress/flate.(*huffmanBitWriter).writeTokens(0xc00b2c8b40, 0xc00bd4a000, 0x4b89, 0xffff, 0xc00ba65200, 0x11e, 0x11e, 0xc00ad58f80, 0x1e, 0x1e)
        /usr/lib/go-1.13/src/compress/flate/huffman_bit_writer.go:583 +0xc3 fp=0xc00bdb0f50 sp=0xc00bdb0f08 pc=0x4e19a3
compress/flate.(*huffmanBitWriter).writeBlockDynamic(0xc00b2c8b40, 0xc00bd4a000, 0x4b89, 0xffff, 0xc00bd08000, 0xc00bd08000, 0xffff, 0xffff)
        /usr/lib/go-1.13/src/compress/flate/huffman_bit_writer.go:528 +0x234 fp=0xc00bdb0fc0 sp=0xc00bdb0f50 pc=0x4e14a4
compress/flate.(*compressor).encSpeed(0xc00bc66000)
        /usr/lib/go-1.13/src/compress/flate/deflate.go:365 +0x319 fp=0xc00bdb1020 sp=0xc00bdb0fc0 pc=0x4dce49
compress/flate.(*compressor).write(0xc00bc66000, 0xc00bed820b, 0x2fb, 0xddf5, 0x5a, 0x0, 0x0)
        /usr/lib/go-1.13/src/compress/flate/deflate.go:551 +0x83 fp=0xc00bdb1060 sp=0xc00bdb1020 pc=0x4ddbc3
compress/flate.(*Writer).Write(...)
        /usr/lib/go-1.13/src/compress/flate/deflate.go:709
compress/zlib.(*Writer).Write(0xc006d90c60, 0xc00bed8000, 0x2fb, 0xe000, 0x5a, 0x0, 0x0)
        /usr/lib/go-1.13/src/compress/zlib/writer.go:154 +0x77 fp=0xc00bdb10c0 sp=0xc00bdb1060 pc=0x4e8497
cmd/link/internal/ld.compressSyms(0xc00069e000, 0xc00b1ce030, 0x6e82, 0xaffa, 0xc00b1ce028, 0x1, 0xaffb)
        /usr/lib/go-1.13/src/cmd/link/internal/ld/data.go:2454 +0x492 fp=0xc00bdb11a0 sp=0xc00bdb10c0 pc=0x567532
cmd/link/internal/ld.dwarfcompress(0xc00069e000)
        /usr/lib/go-1.13/src/cmd/link/internal/ld/dwarf.go:2085 +0x15e fp=0xc00bdb12d0 sp=0xc00bdb11a0 pc=0x57dbee
cmd/link/internal/ld.Main(0x84cdc0, 0x10, 0x20, 0x1, 0x7, 0x10, 0x69ac6f, 0x1b, 0x697756, 0x14, ...)
        /usr/lib/go-1.13/src/cmd/link/internal/ld/main.go:243 +0xcf6 fp=0xc00bdb1428 sp=0xc00bdb12d0 pc=0x5ab546
main.main()
        /usr/lib/go-1.13/src/cmd/link/main.go:65 +0x1d6 fp=0xc00bdb1f60 sp=0xc00bdb1428 pc=0x614616
runtime.main()
        /usr/lib/go-1.13/src/runtime/proc.go:203 +0x21e fp=0xc00bdb1fe0 sp=0xc00bdb1f60 pc=0x42f5de
runtime.goexit()
        /usr/lib/go-1.13/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00bdb1fe8 sp=0xc00bdb1fe0 pc=0x45a511

**Comment by cenkalti** [comment]
`fatal error: runtime: out of memory`

It looks like you are experiencing a memory error. Please write if you need help.
