### ISSUE TITLE
No ability to set custom headers for webseed client

### ISSUE THREAD

**Issue by raprek** [cenkalti/rain#133]
There is a case when the need arises to add headers for `webseedClient` ([code link](https://github.com/cenkalti/rain/blob/master/torrent/session.go#L186)). However there is not method/config setup to set it. Can you add method for example `SetWebseedHeaders` or config param to implement additional headers for webseedClient?

**Comment by cenkalti** [comment]
Yes, I can do that. What's the use case? Do you need to set a header for every webseed download or for a specific domain? Why is this needed?

**Comment by raprek** [comment]
There is need to store stats on weeb seeds side. I use this functionality in libtorret for example. For me it's enough to set user-agent header for session.

**Comment by cenkalti** [comment]
Sorry, I couldn't understand how this feature is going to be used. Can you give more detail please?

Is this header feature required to use a specific tracker or are you building something custom yourself?
