### ISSUE TITLE
What are the router.bittorrent.com connections for?

### ISSUE THREAD

**Issue by NorseGaud** [cenkalti/rain#15]
Hey! Quick question about these:
<img width="1239" alt="Screen Shot 2021-01-09 at 4 27 12 PM" src="https://user-images.githubusercontent.com/5896030/104109004-a6fbef00-5297-11eb-92da-d6eec395d621.png">

Why is rain making connections to bittorrent.com? Any way to disable them?

**Comment by cenkalti** [comment]
These are well known nodes for bootstrapping DHT. You can override them in config or disable DHT completely.
https://github.com/cenkalti/rain/blob/9bd29d7940156f0337fe9c81a21bcc61c37cda64/torrent/config.go#L228-L239
