### ISSUE TITLE
How to both seed and leech

### ISSUE THREAD

**Issue by NorseGaud** [cenkalti/rain#16]
Hey! I'm trying to figure out the best way to have several machines both leech and seed. As of right now, I've got:

Server A (seeder):  
```
datadir: /Users/nathanpierce/Library/Application Support/Veertu
database: seeder.db
datadirincludestorrentid: false
rpcport: 7246
dhtenabled: false
portbegin: 50000
portend: 50001
```

Server B (leecher):
```
datadir: /Users/administrator/Library/Application Support/Veertu
database: leecher.db
datadirincludestorrentid: false
rpcport: 7247
dhtenabled: false
```

Is it as simple as adding `portbegin` and `portend` to the leecher configs on each server and then running `add-peer --addr...` for not only the seeder IP:50000 but also for each leecher I want to also be a seeder?

Let me know if this isn't clear and I'll elaborate. I'd like a single seeder that has the source file and then a bunch of leechers to connect to not only the original seeder but all of the other leechers.

**Comment by cenkalti** [comment]
I don't recommend doing that manually. Add a tracker address while creating the torrent file. You can use a public tracker such as http://opentrackr.org or run yourself one.

If you use a tracker, you will not need to keep track of IP addresses and port numbers.

**Comment by NorseGaud** [comment]
Can rain act as a tracker by chance?

**Comment by cenkalti** [comment]
No, but you can use on of these:
- https://github.com/chihaya/chihaya
- http://erdgeist.org/arts/software/opentracker/
