### ISSUE TITLE
RPC: make it easier to get the torrent file paths

### ISSUE THREAD

**Issue by weberc2** [cenkalti/rain#165]
Thanks for making this project--it's wonderful having a high quality torrent server in the Go ecosystem!

I'm trying to write some automation that will poll the server over RPC to determine when a torrent has finished downloading so I can move it into my media library; however, I don't know how to get information about the downloaded files because the RPC protocol doesn't seem to include the paths to the downloaded files. The only workaround I can think of is to (1) copy the server's download directory configuration to my application (this seems not very nice to keep in sync, but not the end of the world) and (2) to parse the torrent file bytes received over rpc (this requires another library because the metainfo package that rain uses to parse torrent files is marked `internal`).

Ideally, the download paths would be part of the `rpctypes.Torrent` struct (and also there would be a better way to query the server for the torrent corresponding to a download ID rather than having to list the torrents and search--again, not a major problem), but failing that it would be nice to at least expose the `metainfo` package for parsing torrent files on the client side?

Please let me know if there's an easier solution or if I've overlooked something. Thanks!

**Comment by cenkalti** [comment]
Hi @weberc2. I can add the torrent directory into `rpctypes.Torrent`, but that would duplicate information. Each torrent has an ID, and they all download into the session's download directory. After listing torrents and getting IDs, you can check each torrent's status to see if they're completed. You can check the `Status` field or the `Pieces.Total` and `Pieces.Have` fields. Then, copy the contents of the download directory recursively. Does that solve your issue?

**Comment by cenkalti** [comment]
I want to help but would like to understand your use case better. Why can't you download the files inside the torrent's download directory recursively?

I prefer not to make the metainfo package public because that would freeze the API and prevent changes. I want to keep the API at the session and torrent level.

**Comment by weberc2** [comment]
> I want to help but would like to understand your use case better. Why can't you download the files inside the torrent's download directory recursively?

Sure thing! Today, when someone wants to download a torrent, they get a torrent file and provide it to a torrent client like rain to download, and then they have to wait for the download to finish and then move it into their library. For my application, I want the user to be able to provide a torrent _and tell the application which files to copy out of the download directory and where in the user's library to put them_ up front, so the file shows up in the user's library in the right place when the download completes. It would defeat the purpose of my application if the user had to wait for the download to complete before it could tell the application which file to copy out of the download directory because the whole point of my application is to make the torrent step "fire-and-forget" so the user doesn't have to do anything manually when the download finishes.

> I prefer not to make the metainfo package public because that would freeze the API and prevent changes. I want to keep the API at the session and torrent level.

That's understandable. I might be able to find another library that will let me parse the torrent file data. Is the data returned by `Client.GetTorrent()` always bencoded torrent file? Even if the user submits a magnet link?

**Comment by cenkalti** [comment]
Thanks for the explanation. That "fire-and-forget" approach totally makes sense.

`Client.GetTorrent()` returns a bencoded torrent file for transfers added from `.torrent` files. For transfers added from magnet links, it returns a bencoded torrent file after the info dictionary is downloaded from the swarm. Until then, an error is returned.

For getting the list of files, I can expose [Torrent.Files](https://pkg.go.dev/github.com/cenkalti/rain/torrent#Torrent.Files) over RPC. You may not need to parse the torrent file. Does that work for you?

**Comment by weberc2** [comment]
Yes, that should work. Thanks very much!

**Comment by cenkalti** [comment]
I hope this works for you. Please let me know if you have questions.

```bash
❯ rain client files --id iVrZdHOgEe-XgHq05LqvAg
[
  {
    "Length": 1168146432,
    "Path": "archlinux-2024.09.01-x86_64.iso"
  }
]
❯ rain client file-stats --id iVrZdHOgEe-XgHq05LqvAg
[
  {
    "BytesCompleted": 1095270400,
    "File": {
      "Length": 1168146432,
      "Path": "archlinux-2024.09.01-x86_64.iso"
    }
  }
]
```

**Comment by weberc2** [comment]
Thanks again, I think that should work. 👍
