### ISSUE TITLE
Torrent subdir - disable creation

### ISSUE THREAD

**Issue by djdejawu** [cenkalti/rain#175]
After adding the torrent, a directory with a unique name was created in the root directory, for example "IZbelpGEEe-hb1JUAHmUZw", and only after that the torrent files are saved in this subdirectory. How can this be disabled so that all the contents of the torrent are saved in the root directory, and not in this subdirectory?

$ ls -R /Downloads
```
/Downloads/IZbelpGEEe-hb1JUAHmUZw/:
File1.txt
File2.txt
...
```

**Comment by cenkalti** [comment]
It's configurable:
https://github.com/cenkalti/rain/blob/19197767c8e887a38ea50bdb5a7d0e5b61e48ae3/torrent/config.go#L29

**Comment by cenkalti** [comment]
I made this decision because two torrents might have the same file names and collide. I didn't design the client to handle this, so I put them in separate directories to avoid the problem.
