### ISSUE TITLE
Example unusable due to internal calls

### ISSUE THREAD

**Issue by xackery** [cenkalti/rain#18]
when you copy the example main into a file (https://github.com/cenkalti/rain/blob/master/main.go) you get:

        main.go:23:2: use of internal package github.com/cenkalti/rain/internal/console not allowed
        main.go:24:2: use of internal package github.com/cenkalti/rain/internal/logger not allowed
        main.go:25:2: use of internal package github.com/cenkalti/rain/internal/magnet not allowed
        main.go:26:2: use of internal package github.com/cenkalti/rain/internal/metainfo not allowed

**Comment by cenkalti** [comment]
It is not an example. It is the entry point of the program. Please see the example in README file.
