### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by zafer06** [cenkalti/rain#2]
```
zafer@linux:~/go/src$ go get -u github.com/cenkalti/rain
# github.com/cenkalti/rain/torrent
github.com/cenkalti/rain/torrent/session.go:514:18: multiple-value uuid.NewV1() in single-value context

**Comment by cenkalti** [comment]
Hello @zafer06,

Rain uses `dep` tool for vendoring dependencies. I have updated the installation instructions in README: https://github.com/cenkalti/rain#installing

Please note that this software is not production ready yet.
