### ISSUE TITLE
Garbaged/Invalid torrent data can panic the session.AddTorrent method

### ISSUE THREAD

**Issue by bsergean** [cenkalti/rain#23]
```
        body := "some garbage data"
	reader := strings.NewReader(string(body))
	tor, err := session.AddTorrent(reader, nil)
```

This leads to a crash on my box. I can workaround it by using a different library to try to parse the torrent, and avoid calling AddTorrent if it is invalid.

**Comment by cenkalti** [comment]
Added a test case in 7ad0281 for reproducing the issue but it cannot. @bsergean is this still relevant?

**Comment by bsergean** [comment]
I don't think it is. I have a sanity test which I'm gonna remove, and see if I can still reproduce this. Thanks for adding a test case.
