### ISSUE TITLE
Make it possible to override the logging class

### ISSUE THREAD

**Issue by bsergean** [cenkalti/rain#24]
I would like to capture the logs emitted by the library ; I'm using [logrus](https://github.com/sirupsen/logrus).

I don't know what a good interface would look like. Maybe the config could take a Logger class that a user can implement.
See https://github.com/anacrolix/torrent/discussions/551 for example.

ps: I'm a go newbie so take my advice with a grain of salt !

**Comment by cenkalti** [comment]
Good idea 👍
