### ISSUE TITLE
Is there a plan to implement feature : Selective downloading

### ISSUE THREAD

**Issue by kylege** [cenkalti/rain#28]
Hi, i found this repo awesome, but the selective downloading feature is missing, and i think this is a very important feature for some users, is there any plan about this feature's implement?

**Comment by cenkalti** [comment]
Hi @kylege . Sorry, I don't have plans to implement selective downloading feature at the moment.

**Comment by bdwalton** [comment]
FWIW, having poked through the codebase enough at this point, I don't think it would be terribly difficult to add this capability. If it is something you'd accept in the form of contributions, I may poke at it. If it's not something you want in the library at all, that's a different matter. :)

**Comment by cenkalti** [comment]
Thanks @bdwalton. I don't want this feature at the moment as it would increase the code complexity.

**Comment by bdwalton** [comment]
Ack.
