### ISSUE TITLE
Saving to memory instead of disk

### ISSUE THREAD

**Issue by bsergean** [cenkalti/rain#29]
Hi there,

How could the library be extended so that we just download the torrent but don't write it to disk, but to a memory buffer instead ?

Would the idea be to make a 'memory-storage' out of this class/code ?

https://github.com/cenkalti/rain/tree/master/internal/storage

Thanks !

**Comment by cenkalti** [comment]
Yes, that would be great. I think the interface is simple enough to be implemented in memory.

**Comment by cenkalti** [comment]
This may also include some overlapping work for #19 .

**Comment by cenkalti** [comment]
Another resource: https://benjamincongdon.me/blog/2021/01/21/A-Tour-of-Go-116s-iofs-package/

**Comment by cenkalti** [comment]
I would like to help on debugging the issue. Can you elaborate how it is being abused? Is it read or write cache that is being abused? What is the access pattern?

I'd like to give some information about the current state of the read cache.
https://github.com/cenkalti/rain/blob/4bda7a068c561ff7b2ea761e0fe56fdcf49fc2a1/torrent/config.go#L146-L153
When a piece is requested from Rain, it assumes that the peer will request blocks from the same piece again. For that reason, Rain reads more than the actual requested block size. It divides the piece in larger blocks of size `ReadCacheBlockSize` and read all at once.

Example:
Let's assume that torrent piece size is 256K peer will request blocks in size of 16K.
```
0123456789ABCDEF
```
If `ReadCacheBlockSize` is 128K (default value), from the perspective of read cache, torrent piece is divided to 128K blocks.
```
01234567  89ABCDEF
```
In ideal scenario, the peer starts requesting peers from the start in order. When the first block (0) is requested, Rain reads the range between 0 and 7 into memory and caches it. The following requests from 1 to 7 are served directly from cache without going to disk. For the next range between 8 and F, a second read is made from the disk.

**Comment by bsergean** [comment]
I might give this a try, but I noticed that my disk problem was completely unrelated to this library, so feel free to close this ticket, or use it for reference.
