### ISSUE TITLE
panic: already have the piece #987

### ISSUE THREAD

**Issue by bsergean** [cenkalti/rain#37]
Hi there,

I am getting this error a lot, I had changed it to an error, to avoid the panic as this seems not a problem. Is that ok ?

```
rain/torrent/torrent_write.go
44:		panic(fmt.Sprintf("already have the piece #%d", pw.Piece.Index))
```

**Comment by cenkalti** [comment]
I think it is not okay to convert panics to errors. In Rain, panics are considered states that must not happen. Occurrence of a panic indicates a bug in program code, not an error in runtime. I prefer keeping them and handling the unwanted states before reaching that panic.

I've sent a fix to this. I believe it will prevent this particular panic, hence closing the issue. Feel free to comment or re-open if you encounter this again.

**Comment by bsergean** [comment]
Excellent, I will try 3b0d35ea55a24e44d21887c0aafe7c22f2f7e057 and report whether it fixes things (I hope so) / I was getting this error often so I should know pretty fast.
