### ISSUE TITLE
Removed torrent directory after download

### ISSUE THREAD

**Issue by dd4e** [cenkalti/rain#48]
Hello! 

I found a stranger thing, I think it's a bug. 

Todo:

- `DataDirIncludesTorrentID = true`
- I have a torrent in the session with a custom ID
- I need to download a new torrent with the same ID
- I use [Session.RemoveTorrent](https://pkg.go.dev/github.com/cenkalti/rain/torrent#Session.RemoveTorrent) before adding a new torrent
- Next, I add a new torrent to the session
- After the end of downloading the new torrent, the directory does not exist

I think that happened because of [the func](https://github.com/cenkalti/rain/blob/6473c390f30b81e7f7dccdc4881d799dc177c7f9/torrent/session.go#L336) running as goroutine and it has run after the end download the new torrent.

I think it will be a good thing to reduce the goroutine to a func

**Comment by cenkalti** [comment]
Good catch @dd4e. I'll send a fix in few minutes...
