### ISSUE TITLE
Status: Stopped: file allocation error

### ISSUE THREAD

**Issue by derit** [cenkalti/rain#52]
previously, i nothing issue using rain as torrent client, currently i have an issue when i download a file with size 104597 MiB , i'm not sure this issue about size

here general info about my torrent

```
Name: Mytorrent-test
Private: false
Status: Stopped: file allocation error: open /root/rain/data/CsifRcHWEeyOJwLUlt2y4A/Mytorrent-test/media/Stripped/MediaOverride/x10/test/CHARACTER_Driver.zip: too many open files
Progress: 0%
Ratio: 0.00
Size: 104597 MiB
Peers: 0 in / 0 out
Download speed:     0 KiB/s
Upload speed:       0 KiB/s
ETA:
```

**Comment by cenkalti** [comment]
How many files does your torrent contains? It probably has more than 10240. You can set it to higher value.
https://github.com/cenkalti/rain/blob/790f0496cd640c03b83656f586ccbeed0a62b4a4/torrent/config.go#L201

Rain will try to increase the limit to the value set in the config. Or, you can set it with `ulimit -n` command before running Rain.

**Comment by derit** [comment]
@cenkalti files count in mytorrent is `10154`

**Comment by derit** [comment]
and i'm was increase ulimit but not work
```
ulimit -n
65535
```

**Comment by derit** [comment]
solved:
i set config MaxOpenFiles increase default value to `65535`
