### ISSUE TITLE
remove or edit peer and tracker

### ISSUE THREAD

**Issue by derit** [cenkalti/rain#73]
how to remove peer and tracker ?

this is an example on qbittorrent
![image](https://user-images.githubusercontent.com/5389364/189527198-3a151f7d-e8ef-49c0-b935-5d3397ab1c85.png)

![image](https://user-images.githubusercontent.com/5389364/189527266-be65cf95-99f0-441c-ae41-dc8ef58c0673.png)

**Comment by cenkalti** [comment]
This feature is not implemented yet.

**Comment by derit** [comment]
@cenkalti  do you know why this error issue? 
my assume this is from tracker url is invalid ? or you have an experience about this

![image](https://user-images.githubusercontent.com/5389364/189535389-e8e72bc2-b1f0-43d2-9576-d001dfd410c8.png)

**Comment by cenkalti** [comment]
If `Error` starts with `announce error:` it means that it comes from the tracker and Rain directly shows it to you without changing.

"Torrent not registered" usually means that the tracker does not know anything about the torrent you are downloading, hence cannot send you a peer list that you can connect to.

**Comment by derit** [comment]
can you explain to me, when i check peers list on this torrent, why have many peer on whis torrent and have announce error, this torrent only have only single tracker

**Comment by cenkalti** [comment]
If it's a public torrent, client can also utilize other mechanisms to find peers such as DHT and PEX.

**Comment by derit** [comment]
okey thanks
