### ISSUE TITLE
Starts seeding after verification for incomplete torrent

### ISSUE THREAD

**Issue by ufukomer** [cenkalti/rain#8]
**Action:** Delete one of the –or all of the– files of a completed torrent manually. Then start the torrent.
**Expectation:** Run verification to define missing pieces then download and start seeding after completion.
**Behaviour:** It automatically runs verification process and torrent progress is now lower than 100 but rather than re-downloading the missing pieces, it starts seeding.

If I restart the server it starts downloading the missing parts. However, without restarting the server,`rain client start` is just starts seeding. I've also tried manuel verification but the result is same. How can I download the missing pieces without restarting server or removing torrent completely?

<img width="324" alt="Screen Shot 2019-12-19 at 1 40 09 AM" src="https://user-images.githubusercontent.com/7649229/71129868-87fc6c00-2201-11ea-9b99-f24f787167c8.png">

P.S: Configuration is same as default except `DHTMinAnnounceInterval` which is 10 seconds.

**Comment by cenkalti** [comment]
I can also confirm this behavior. Definitely will check it out.
