### ISSUE TITLE
Support for BitComet  Padding files

### ISSUE THREAD

**Issue by kylege** [cenkalti/rain#80]
Hi, @cenkalti , do you have the time to add support for bitcomet's padding files?

https://en.wikipedia.org/wiki/BitComet#Padding_files

http://bittorrent.org/beps/bep_0047.html

rain should just ignore these padding files.

**Comment by cenkalti** [comment]
Started on it: https://github.com/cenkalti/rain/compare/pad?expand=1

Hiding padding files is easy. I think the challenging part is calculating piece block boundaries to skip downloading padding blocks from peers.
