### ISSUE TITLE
Allow for multiple torrents listening on a port

### ISSUE THREAD

**Issue by chiefnoah** [cenkalti/rain#9]
I understand it's outside the main use-case for Rain, but in a more traditional setup, binding to a port for each torrent is not necessary and may result in collisions if other services are running in the range of allowed ports.

I've been looking through the code a bit, but I'm not very familiar with the specifics of the BitTorrent protocol. I doubt it's as simple as passing in a shared TCPListener to [`acceptor.new()`](https://github.com/cenkalti/rain/blob/master/torrent/torrent_start.go#L121), but maybe it is?

**Comment by cenkalti** [comment]
@chiefnoah It's actually more complicated than that. I have take a quick look but it is something that needs to be thought carefully and when it is done, it will make the code more complicated. Thus, I am marking this issue as "wontfix" for now.
